import { getServerSidePropsWithAuthDefaults } from "@/authUtils.ts";
import Head from "next/head";

export const getServerSideProps = getServerSidePropsWithAuthDefaults(
  async () => {
    return { props: {} };
  },
);

export default function Home() {
  return (
    <>
      <Head>
        <title>USU FSLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>USU Free Software And Linux Club</h1>
        <p>
          We are a club at Utah State University dedicated to teaching about and
          encouraging the everyday use of Linux-based operating systems as well
          as Free and Open-Source Software (FOSS).
        </p>
        <h2>Meetings</h2>
        <p>
          Over the summer, we hold meetings <strong>every Wednesday</strong> at{" "}
          <strong>6:00 pm</strong> in <strong>ESLC 053</strong> (check our
          Discord for more information). There are no presentations, just
          hacking and chatting.
        </p>
        <ul>
          <li>
            <strong>March 25</strong>: Linux system administration, from an
            expert
          </li>
          <li>
            <strong>April 1</strong>: SystemU (SystemD and You)
          </li>
          <li>
            <strong>April 8</strong>: Proving code mathematically with SMT
          </li>
          <li>
            <strong>April 15</strong>: Algebraic effects
          </li>
        </ul>
        <p>
          If you have something to talk about or something you want to learn, we
          can help!{" "}
          <strong>
            Fill out <a href="https://forms.gle/7xS5avngKivdrA7V8">this form</a>
          </strong>{" "}
          and we can make it happen.
        </p>
        <p>
          To watch broadcasts live, you can go to{" "}
          <strong>
            <a href="https://stream.linux.usu.edu">stream.linux.usu.edu</a>
          </strong>
          .
        </p>
        <h2>Discord</h2>
        <p>
          <strong>
            Join us on <a href="https://discord.gg/PvgG6N2hsU">Discord</a>
          </strong>{" "}
          for support if you need help with your Linux installation, or to talk
          about computer science with us, or simply to hang out!
        </p>
        <p>
          You&apos;ll also get meeting schedules as soon as they come out as
          well as information about other club appearances.
        </p>
        <h2>IRC</h2>
        <p>
          We also have an IRC channel now, if you hate Discord. We can&apos;t
          guarantee you&apos;ll get a prompt reply, but it is there for you. We
          can be found at{" "}
          <a href="irc:irc.libera.chat/##usufslc">##usufslc on libera.chat</a> (
          <a href="https://web.libera.chat/##usufslc">web access</a>).
        </p>
        <h2>Hardware</h2>
        <p>
          Want to build your own self-hosted project? The FSLC has plenty of
          computers that we can lend you to hack on for free (as in free pizza).
          Join the Discord server to ask.
        </p>
      </main>
    </>
  );
}
