import { getServerSidePropsWithAuthDefaults } from "@/authUtils.ts";
import Head from "next/head";
import Link from "next/link";

export const getServerSideProps = getServerSidePropsWithAuthDefaults(
  async () => {
    return { props: {} };
  },
);

export default function Home() {
  return (
    <>
      <Head>
        <title>USU FSLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>USU Free Software And Linux Club</h1>
        <p>
          We are a club at Utah State University dedicated to teaching about and
          encouraging the everyday use of Linux-based operating systems as well
          as Free and Open-Source Software (FOSS).
        </p>
        <h2>Meetings</h2>
        <p>
          This semester, we will be holding meetings{" "}
          <strong>every Tuesday</strong> at <strong>6:30 pm</strong> in{" "}
          <strong>ESLC 053</strong>
          (check our Discord for more information). See{" "}
          <strong>
            <Link href="/calendar">the calendar page</Link>
          </strong>{" "}
          for upcoming events. Also, all of our meetings are streamed! See{" "}
          <strong>
            <Link href="/stream">the stream page</Link>
          </strong>{" "}
          for ongoing streams.
        </p>
        <p>
          If you have something to talk about or something you want to learn, we
          can help!{" "}
          <strong>
            Fill out <a href="https://forms.gle/7xS5avngKivdrA7V8">this form</a>
          </strong>{" "}
          and we can make it happen.
        </p>
        <h2>EndOf10</h2>
        <p>
          Did you know? Microsoft is ending support for Windows 10 on{" "}
          <strong>October 14</strong>. The FSLC is partnered with{" "}
          <a href="https://endof10.org/">EndOf10</a> to provide help to those
          who want to <strong>switch to Linux</strong> instead of buying a new
          computer. Get in contact with us to learn more!
        </p>
        <h2>Discord</h2>
        <p>
          <strong>
            Join us on <a href="https://discord.gg/PvgG6N2hsU">Discord</a>
          </strong>{" "}
          for support if you need help with your Linux installation, or to talk
          about computer science with us, or simply to hang out!
        </p>
        <p>
          You&apos;ll also get meeting schedules as soon as they come out as
          well as information about other club appearances.
        </p>
        <h2>IRC</h2>
        <p>
          We also have an IRC channel now, if you hate Discord. We can&apos;t
          guarantee you&apos;ll get a prompt reply, but it is there for you. We
          can be found at{" "}
          <a href="irc:irc.libera.chat/##usufslc">##usufslc on libera.chat</a> (
          <a href="https://web.libera.chat/##usufslc">web access</a>).
        </p>
        <h2>Hardware</h2>
        <p>
          Want to build your own self-hosted project? The FSLC has plenty of
          computers that we can lend you to hack on for free (as in free pizza).
          Join the Discord server to ask.
        </p>
      </main>
    </>
  );
}
